config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :snippets
  resources :languages, only: [:show]

  root "snippets#index"

end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :snippets, dependent: :nullify

  validates :name, uniqueness: true, presence: true

end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  belongs_to :user
  belongs_to :language
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :snippets, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  def show
    @language = Language.find params[:id]
    @snippets = @language.snippets
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :find_snippet, only: [:show, :edit, :update, :destroy]
  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = Snippet.new snippet_params
    if @snippet.save
      redirect_to snippet_path(@snippet), notice: "Snippet Created"
    else
      redirect_to new_snippet_path, alert: "Failed to Create Snippet!"
    end
  end

  def index
    @snippets = Snippet.all
    @languages = Language.all
  end

  def show
  end

  def edit
  end

  def update
    if @snippet.update snippet_params
      redirect_to snippet_path(@snippet), notice: "Update Successfully"
    else
      flash[:alert] = "Failed to Update"
      render :edit
    end
  end

  def destroy
    @snippet.destroy
    redirect_to root_path, notice: "Snippet Deleted"
  end

  private

  def find_snippet
    @snippet = Snippet.find params[:id]
  end

  def snippet_params
    params.require(:snippet).permit(:title, :body, :language_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  class CodeRayify < Redcarpet::Render::HTML
   def block_code(code, language)
     CodeRay.scan(code, language).div
   end
  end

  def markdown(text)
   coderayified = CodeRayify.new(:filter_html => true,
                                 :hard_wrap => true)
   options = {
     :fenced_code_blocks => true,
     :no_intra_emphasis => true,
     :autolink => true,
     :lax_html_blocks => true,
   }
   markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
   markdown_to_html.render(text).html_safe
  end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/languages/show.html.erb
<h1><%= @language.name %></h1>

<% @snippets.each do |s| %>
	<h2><%= link_to s.title, snippet_path(s) %></h2>
	Category: <%= s.language.name %>
	<%= markdown("~~~~~#{s.language.name.downcase}\n"+s.body+"\n~~~~~") %>
	<hr>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PersonalPage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default">
		<div class="container">
			<div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-menu" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to "LOGO", root_path, {class: "navbar-brand"} %>
	    </div><!-- .navbar-header -->

	      <div class="collapse navbar-collapse" id="top-menu">
					<ul class="nav navbar-nav navbar-right">
		        <li><%= link_to "Add New Snippet", new_snippet_path %></li>
		        <li><%= link_to "Login", "#" %></li>
		        <li><%= link_to "Sign Up", "#" %></li>
		      </ul>
	      </div><!-- .collapse .navbar-collapse -->
		</div><!-- .container -->
	</nav>

	<div class="main-content">
		<div class="container">
			<%= yield %>
		</div><!-- .container -->
	</div><!-- .main-content -->

</body>
</html>

app/views/snippets/_form.html.erb
<%= form_for @snippet do |f| %>
  <div>
    <%= f.collection_select :language_id, Language.order(:name), :id, :name %>
  </div>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: "Enter title here..."  %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body, placeholder: "Enter your code here..."  %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/snippets/edit.html.erb
<%= render "/snippets/form" %>

app/views/snippets/index.html.erb
<h1>All Snippets</h1>

<% @snippets.each do |s| %>
	title: <%= s.title %>
	<%= markdown("~~~~~#{s.language.name.downcase}\n"+s.body+"\n~~~~~") %>
	<hr>
<% end %>

app/views/snippets/new.html.erb
<h1>Add a new code snippet</h1>
<%= render "/snippets/form" %>

app/views/snippets/show.html.erb
<h1>Title: </h1>
  <%= @snippet.title %>
<h1>Body: </h1>
  <%= markdown("~~~~~#{@snippet.language.name.downcase}\n"+@snippet.body+"\n~~~~~") %>
<%= link_to "Edit", edit_snippet_path(@snippet)%>
<%= link_to "Delete", snippet_path(@snippet),
                      method: :delete,
                      data: {confirm: "Are you sure"}%>